name: Synk Scan Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk-scan:
    name: Snyk Security Scan
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3
        
        
      # Set up Java environment
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # Specify the Java version you need

      # Set up Node.js environment (needed for Snyk CLI)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Or any other required version
      
      # Generate mvnw using wrapper
      - name: Generate Maven Wrapper
        working-directory: ./green-global-initiative-api
        run: mvn wrapper:wrapper
       
      # Check if mvnw exists
      - name: Check if mvnw exists
        run: ls -l ./green-global-initiative-api/mvnw


      # Verbose Output for Debugging
      - name: List files in green-global-initiative-api
        run: ls -l ./green-global-initiative-api/mvnw

      # Make mvnw executable with Debugging
      - name: Make mvnw executable
        working-directory: green-global-initiative-api
        run: |
          chmod +x ./mvnw
          ls -l ./mvnw  # Verify permissions after running chmod
      
      - name: Run mvn dependency check
        working-directory: ./green-global-initiative-api
        run: ./mvnw dependency:tree -DoutputType=dot --batch-mode --non-recursive --file="pom.xml"
       
      # Check For Access rights
      - name: Check file permissions
        run: stat ./green-global-initiative-api/mvnw

      # Install Snyk CLI
      - name: Install Snyk CLI
        run: npm install -g snyk

      # Authenticate Snyk using the token
      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
        
      # Run Snyk scan for Java
      - name: Run Snyk test for Java dependencies
        working-directory: green-global-initiative-api
       # run: snyk test --file=pom.xml --severity-threshold=high 
        run: snyk test --file=pom.xml --severity-threshold=high -d
        
        
      # Optional Step: Monitor project on Snyk dashboard
      - name: Monitor Snyk project
        working-directory: green-global-initiative-api
        run: snyk monitor --file=pom.xml
        
        
      # Run Snyk scan for dependencies
      #- name: Run Snyk scan
      #  run: snyk test

      # Run Snyk scan for Infrastructure as Code (IaC)
     # - name: Run Snyk IaC scan
     #   run: snyk iac test
