name: Deploy to EKS

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch (modify as necessary)

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up AWS credentials
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Configure kubectl for EKS
      - name: Set up kubectl
        run: |
          aws eks update-kubeconfig --name dev-eks-cluster --region ${{ secrets.AWS_REGION }}

      # Step 4: Deploy Kubernetes Manifests to EKS
      - name: Deploy Kubernetes Manifests to EKS
        working-directory: ./Kubernetes-Manifest-Files
        run: |
          kubectl create namespace three-tier || echo "Namespace already exists"
          kubectl apply -f ./Kubernetes-Manifest-Files/
          
          # Optional: Verify if deployments are successful
          kubectl get all --namespace three-tier
