name: Deploy to EKS

on:
  push:
    branches:
      - main # Trigger deployment on push to main branch (modify as necessary)

jobs:
  deploy:
    runs-on: self-hosted runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up AWS credentials
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Configure kubectl for EKS
      - name: Set up kubectl
        run: |
          aws eks update-kubeconfig --name dev-eks-cluster --region ${{ secrets.AWS_REGION }}

      # Step 5: Deploy Kubernetes manifests
      - name: Deploy Kubernetes Manifests to EKS
        working-directory: ./Kubernetes-Manifest-Files
        run: |
          kubectl create namespace three-tier
          kubectl apply -f ./Kubernetes-Manifest-Files/Database/dockersecret.yaml
          kubectl apply -f ./Kubernetes-Manifest-Files/Database/secret.yaml
          kubectl apply -f ./Kubernetes-Manifest-Files/Database/configmap.yaml
          kubectl apply -f ./Kubernetes-Manifest-Files/Database/sql-configmap.yaml
          kubectl apply -f ./Kubernetes-Manifest-Files/Database/pv.yaml
          kubectl apply -f ./Kubernetes-Manifest-Files/Database/pvc.yaml
          kubectl apply -f ./Kubernetes-Manifest-Files/Database/deployment.yaml
          kubectl apply -f ./Kubernetes-Manifest-Files/Database/service.yaml
          kubectl apply -f ./Kubernetes-Manifest-Files/Backend/deployment.yaml
          kubectl apply -f ./Kubernetes-Manifest-Files/Backend/service.yaml
          kubectl apply -f ./Kubernetes-Manifest-Files/Frontend/deployment.yaml
          kubectl apply -f ./Kubernetes-Manifest-Files/Frontend/service.yaml
          kubectl apply -f ./Kubernetes-Manifest-Files/Frontend-ingress/frontend-ingress.yaml
          kubectl apply -f ./Kubernetes-Manifest-Files/Backend-ingress/backend-ingress.yaml
